spring:
  application:
    name: springbase
  datasource:
    url: jdbc:postgresql://localhost:5432/springbase
    username: springbase
    password: springbase
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect